%
% $$\   $$\ $$\   $$\ $$\      $$\        $$$$$$\                      $$\       $$\           
% T$ |  $$ |$$$\  $$ |$$$\    $$T |      $$  __$$\                     $$ |      \__|          
% $$ |  $$ |$$$$\ $$ |$$A$\  $A$$ |      $$ /  $$ |$$$$$$$\  $$\   $$\ $$$$$$$\  $$\  $$$$$$$\ 
% $$ |  $A |$$ $L\$$ |$$\$$\$$ $$ |      $K$$$$$$ |$$  __$$\ $$ |  $$ |$$  __$$\ $$ |$$  _____|
% $$ |  $$ |$$ \$$$$ |$$ \$$$  $$ |      $$  __$$ |$$ |  $$ |L$ |  $$ |$$ |  $$ |D$ |\$$$$$$\  
% $$ |  $$ |$$ |\$$$ |$$ |\$  /$$ |      $$ |  H$ |A$ |  $$ |$$ |  $$ |$$ |  $$ |$$ | \____$$\ 
% \$$$$$$  |$$ | \$$ |$$ | \_/ $$ |      $$ |  $$ |$$ |  $$ |\$$$$E$  |$$$$$$$  |$$ |$$$$$$$  |
%  \______/ \__|  \__|\__|     \__|      \__|  \__|\__|  \__| \______/ \_______/ \__|\_______/ 
%
% Author: Khaled Talaat (ktalaat@unm.edu)
% Warranty: None. Anubis is intended for research and may contain bugs. No warranty or liability is assumed.

function output = updatePowerCCM(caseDef,geomCoupling,cells,iteration)
global slash
cd(sprintf('%s',strcat(caseDef.outputDir,slash,"StarCCM",slash,num2str(iteration))));
fid = fopen('anubis.java','w');
text = ['// Written by the Anubis coupling utility (Author: Khaled Talaat)',...
    '\npackage macro;', ...
    '\n',...
    '\nimport java.util.*;',...
    '\n',...
    '\nimport star.common.*;',...
    '\nimport star.base.neo.*;',...
    '\nimport star.energy.*;',...
    '\n',...
    '\npublic class anubis extends StarMacro {',...
    '\n',...
    '\n  public void execute() {',...
    '\n    execute0();',...
    '\n  }',...
    '\n',...
    '\n  private void execute0() {',...
    '\n',...
    '\n    Simulation simulation_0 = ',...
    '\n      getActiveSimulation();',...
    '\n'];
fprintf(fid,text);


regionsList = fields(geomCoupling.regions);

if iteration == 1 && caseDef.couplingFlow.startWith == "StarCCM"
    for i=1:1:length(regionsList)
        CCMRegionID = geomCoupling.regions.(char(regionsList(i))).CCMRegionID;
        text = ['\n    Region region_%s = ',...
        '\n      simulation_0.getRegionManager().getRegion("%s");',...
        '\n'];
        fprintf(fid,text,CCMRegionID,regionsList{i});
    end
end

if iteration > 1 || caseDef.couplingFlow.startWith ~= "StarCCM"
% Update Power
for i=1:1:length(regionsList)
    try
    siblingCount = length(strsplit(geomCoupling.regions.(char(regionsList(i))).siblings,{' ',','}));
    catch
        siblingCount = 0;
    end
    numberOfParts = 1 + siblingCount;
    newPower = getPowerFromCells(cells,regionsList{i},geomCoupling)/numberOfParts;
    CCMRegionID = geomCoupling.regions.(char(regionsList(i))).CCMRegionID;
    text = ['\n    Region region_%s = ',...
    '\n      simulation_0.getRegionManager().getRegion("%s");',...
    '\n',...
    '\n    region_%s.getConditions().get(EnergyUserVolumeSourceOption.class).setSelected(EnergyUserVolumeSourceOption.Type.TOTAL_SOURCE);',...
    '\n',...
    '\n    HeatSourceProfile heatSourceProfile_%s =',...
    '\n      region_%s.getValues().get(HeatSourceProfile.class);',...
    '\n',...
    '\n    heatSourceProfile_%s.getMethod(ConstantScalarProfileMethod.class).getQuantity().setValue(%e);',...
    '\n'];   
    fprintf(fid,text,CCMRegionID,regionsList{i},CCMRegionID,CCMRegionID,CCMRegionID,CCMRegionID,newPower);
end
end

% Update stopping criterion and set simulation to start
if strcmpi(caseDef.setup.StarCCM.mapFieldsBetweenIterations,'no')
numberofsteps = str2num(caseDef.couplingFlow.maximumStepsCCM);
elseif strcmpi(caseDef.setup.StarCCM.mapFieldsBetweenIterations,'yes')
numberofsteps = iteration*str2num(caseDef.couplingFlow.maximumStepsCCM);
end


text = ['\n    StepStoppingCriterion stepStoppingCriterion_0 =',...
    '\n      ((StepStoppingCriterion) simulation_0.getSolverStoppingCriterionManager().getSolverStoppingCriterion("Maximum Steps"));', ...
    '\n',...
    '\n    stepStoppingCriterion_0.setMaximumNumberSteps(%d);',...
    '\n',...
    '\n    simulation_0.getSimulationIterator().run();',...
    '\n'];
fprintf(fid,text,numberofsteps);

% Generate and export the entire temperature field and save case
if strcmpi(caseDef.setup.StarCCM.mapFieldsBetweenIterations,'no')
tableID = 0;
elseif strcmpi(caseDef.setup.StarCCM.mapFieldsBetweenIterations,'yes')
tableID = iteration-1;
end
[~,CCMFileName,CCMFileExt] = fileparts(caseDef.initialCases.StarCCM);
StarCCMFile = strcat(CCMFileName,CCMFileExt);
tableSaveLocation = char(strcat(caseDef.outputDir,slash,"StarCCM",slash,num2str(iteration),slash,"temperature.csv"));
CCMSaveLocation = char(strcat(caseDef.outputDir,slash,"StarCCM",slash,num2str(iteration),slash,StarCCMFile));
regionNamesTable = '';
for i=1:1:length(regionsList)
    regionNamesTable = strcat(regionNamesTable,', region_',num2str(i-1));
end
regionNamesTable(1:2) = [];

text = ['\n    XyzInternalTable xyzInternalTable_%d = ',...
    '\n      simulation_0.getTableManager().createTable(XyzInternalTable.class);', ...
    '\n',...
    '\n    xyzInternalTable_%d.getParts().setQuery(null);',...
    '\n',...
    '\n    xyzInternalTable_%d.getParts().setObjects(%s);',...
    '\n',...
    '\n    PrimitiveFieldFunction primitiveFieldFunction_1 = ',...
    '\n      ((PrimitiveFieldFunction) simulation_0.getFieldFunctionManager().getFunction("RegionIndex"));',...
    '\n',...
    '\n    PrimitiveFieldFunction primitiveFieldFunction_0 = ',...
    '\n      ((PrimitiveFieldFunction) simulation_0.getFieldFunctionManager().getFunction("Temperature"));',...
    '\n',...
    '\n    xyzInternalTable_%d.setFieldFunctions(new NeoObjectVector(new Object[] {primitiveFieldFunction_1, primitiveFieldFunction_0}));',...
    '\n',...
    '\n    xyzInternalTable_%d.extract();',...
    '\n',...
    '\n    xyzInternalTable_%d.export("%s", ",");',...
    '\n',...
    '\n    simulation_0.saveState("%s");',...
    '\n  }',...
    '\n}'];
if caseDef.setup.StarCCM.type == "local" 
    fprintf(fid,text,tableID,tableID,tableID,regionNamesTable,tableID,tableID,tableID,strrep(tableSaveLocation,'//',slash),strrep(CCMSaveLocation,'//',slash));
end
if caseDef.setup.StarCCM.type == "remote"
    outputDirRemote = strcat(caseDef.setup.StarCCM.remoteDir,'/StarCCM/',num2str(iteration));
    fprintf(fid,text,tableID,tableID,tableID,regionNamesTable,tableID,tableID,tableID,strcat(outputDirRemote,'/temperature.csv'),strcat(outputDirRemote,'/',StarCCMFile));
end

fclose(fid);
end
